<?php

namespace Database\Seeders;

use App\Models\Addon;
use App\Models\Association;
use App\Models\Category;
use App\Models\Contact;
use App\Models\Hotel;
use App\Models\Itinerary;
use App\Models\Programme;
use App\Models\Roadmap;
use App\Models\Speaker;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Root',
            'role' => 'Root',
            'email' => 'admin@paqs2025.com',
            'password' => Hash::make('password'),
        ]);

        Addon::insert([
            [
                'id' => 1,
                'name' => 'PAQS Golf 2024',
                'price' => '250',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Association::insert([
            [
                'id' => 1,
                'name' => 'ASAQS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'BSIJ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'CCEA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'CIQS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'HKIS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'ICEC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'IQSI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'IQSSL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'NZIQS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'PAQS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'PICQS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'PUJA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'RISM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'SISV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Category::insert([
            [
                'name' => 'IQSI Member (Main Congress & Gala Dinner)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '3500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NON - IQSI (Main Congress & Gala Dinner)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '4500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Main Congress',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '3500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Student (Main Congress)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '3000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Student (YQS)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '2000000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Student (Main Congress & YQS)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '4750000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAQS GOLF 2025 (Member IQSI)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '2500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAQS GOLF 2025 (Non - Member)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '3500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Networking Dinner (Professional, Construction Industries, Suppliers, and others)',
                'type' => 'Congress Fee (Indonesia)',
                'currency' => 'IDR',
                'price' => '2500000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAQS Member (Pre Congress, Main Congress & Gala Dinner)',
                'type' => 'Congress Fee (Non-Indonesia)',
                'currency' => 'USD',
                'price' => '850',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NON - PAQS (Main Congress & Gala Dinner)',
                'type' => 'Congress Fee (Non-Indonesia)',
                'currency' => 'USD',
                'price' => '950',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Early Bird',
                'type' => 'Congress Fee (Non-Indonesia)',
                'currency' => 'USD',
                'price' => '770',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAQS GOLF 2025 (Member)',
                'type' => 'Congress Fee (Non-Indonesia)',
                'currency' => 'USD',
                'price' => '160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAQS GOLF 2025 (Non - Member)',
                'type' => 'Congress Fee (Non-Indonesia)',
                'currency' => 'USD',
                'price' => '185',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spouse Program',
                'type' => 'Congress Fee (Non-Indonesia)',
                'currency' => 'USD',
                'price' => '95',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Contact::insert([
            [
                "name" => "Retno Dwi (Eno)",
                "telephone" => "+6281211116900",
                "image" => "profile picture - woman.jpg",
            ],
            [
                "name" => "Rizka",
                "telephone" => "+6282125917021",
                "image" => "profile picture - woman.jpg",
            ],
            [
                "name" => "Geraldine",
                "telephone" => "+628114030903",
                "image" => "profile picture - woman.jpg",
            ],
            [
                "name" => "Graha",
                "telephone" => "+6282280286961",
                "image" => "profile picture - woman.jpg",
            ],
        ]);

        Hotel::insert([
            [
                "id" => 1,
                "name" => "Ascott Kuningan Jakarta",
                "star" => 5,
                "telephone" => "02130060288",
                "location" => "https://maps.app.goo.gl/2hDkjgPZUE2GxFVNA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "name" => "Somerset Grand Citra",
                "star" => 5,
                "telephone" => "02129956888",
                "location" => "https://maps.app.goo.gl/iSAELWMdvGuqFjVa6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "name" => "Oakwood Premier Cozmo",
                "star" => 5,
                "telephone" => "02125542300",
                "location" => "https://maps.app.goo.gl/Kq7wXFnoQt2yijog9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "name" => "JW Mariott Hotel",
                "star" => 5,
                "telephone" => "02157988888",
                "location" => "https://maps.app.goo.gl/5M59iHnjPxpxYVJd6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "name" => "The Ritz-Carlton Jakarta, Mega Kuningan",
                "star" => 5,
                "telephone" => "02125518888",
                "location" => "https://maps.app.goo.gl/ATK6Hk3gWTxPcYrZ9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "name" => "Four Seasons",
                "star" => 5,
                "telephone" => "02122771888",
                "location" => "https://maps.app.goo.gl/NvtwDR8De3cTCQzh9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "name" => "The Grove Suites by Grand Aston",
                "star" => 5,
                "telephone" => "02129941880",
                "location" => "https://maps.app.goo.gl/Py4wFsEeoBpgbPY4A",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "name" => "Hotel Indonesia Kempinski Jakarta",
                "star" => 5,
                "telephone" => "02123583800",
                "location" => "https://maps.app.goo.gl/WnzeFd3A4V7MMNBT8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "name" => "The Westin Jakarta",
                "star" => 5,
                "telephone" => "02127887788",
                "location" => "https://maps.app.goo.gl/zgeadkgexv8zFyjF9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "name" => "Gran Melia Jakarta",
                "star" => 5,
                "telephone" => "0215268080",
                "location" => "https://maps.app.goo.gl/rbKEd9hnLtVwGafLA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "name" => "JS Luwansa ",
                "star" => 4,
                "telephone" => "02129543030",
                "location" => "https://maps.app.goo.gl/1tLftrp7giNXgAFq6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 12,
                "name" => "Mangkuluhur ARTOTEL Suites",
                "star" => 4,
                "telephone" => "0215268833",
                "location" => "https://maps.app.goo.gl/F1sKj3Dz9Y5YXC7v5",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 13,
                "name" => "Mercure Jakarta Gatot Subroto",
                "star" => 4,
                "telephone" => "02150825400",
                "location" => "https://maps.app.goo.gl/1BuNYyyg1skU9ceu7",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 14,
                "name" => "Novotel Jakarta Cikini",
                "star" => 4,
                "telephone" => "02131937777",
                "location" => "https://maps.app.goo.gl/Nbe3d3A3nfanM81c6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 15,
                "name" => "Aryaduta Menteng",
                "star" => 4,
                "telephone" => "02123521234",
                "location" => "https://maps.app.goo.gl/DufsvCUFN1FCknrZ8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 16,
                "name" => "Citadines Sudirman Jakarta",
                "star" => 4,
                "telephone" => "02139738080",
                "location" => "https://maps.app.goo.gl/xUEKmA4YYrMM1vqE9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 17,
                "name" => "Habitare Rauna Jakarta",
                "star" => 4,
                "telephone" => "+628118129533",
                "location" => "https://maps.app.goo.gl/g6qXvrNNVuGjMvg66",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 18,
                "name" => "Ayaka Suites",
                "star" => 3,
                "telephone" => "02129037380",
                "location" => "https://maps.app.goo.gl/AED5Fisf5UTvYrWS9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 19,
                "name" => "Miers Kuningan, ARTOTEL Curated",
                "star" => 3,
                "telephone" => "02157851751",
                "location" => "https://maps.app.goo.gl/FMKynKjiPcgnfy3HA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 20,
                "name" => "D'Bamboo Suites",
                "star" => 3,
                "telephone" => "0811-9004-815",
                "location" => "https://maps.app.goo.gl/MhvDuYddyFi43Gb58",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 21,
                "name" => "Hotel D' Prima",
                "star" => 3,
                "telephone" => "02129201234",
                "location" => "https://maps.app.goo.gl/9MgEemHQX4VzqN5g9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 22,
                "name" => "Rasuna Icon Hotel",
                "star" => 3,
                "telephone" => "0215201642",
                "location" => "https://maps.app.goo.gl/crtT2a6pYsEtWAdTA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 23,
                "name" => "Avissa Suites",
                "star" => 3,
                "telephone" => "02152960022",
                "location" => "https://maps.app.goo.gl/krxo9Kj2MpnC16CA9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 24,
                "name" => "favehotel Gatot Subroto Jakarta",
                "star" => 3,
                "telephone" => "02129419888",
                "location" => "https://maps.app.goo.gl/toVwDAmMjb6gkxKE8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 25,
                "name" => "Yello Hotel Manggarai",
                "star" => 3,
                "telephone" => "02130428888",
                "location" => "https://maps.app.goo.gl/y2jmpLgpHXJAP65M9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 26,
                "name" => "Pomelotel Patra Kuningan Jakarta",
                "star" => 3,
                "telephone" => "02183709588",
                "location" => "https://maps.app.goo.gl/5w2eWhd497ZHAHzb7",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 27,
                "name" => "Daun Residence Kuningan",
                "star" => 3,
                "telephone" => "02125984108",
                "location" => "https://maps.app.goo.gl/YARYc2uqHMEmBtuT8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 28,
                "name" => "Nostoi",
                "star" => 3,
                "telephone" => "081280393849",
                "location" => "https://maps.app.goo.gl/JCumnJ5vBspqKNEz5",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);

        Itinerary::insert([
            [
                'day' => 1,
                'time_1' => '08:45:00',
                'time_2' => '09:00:00',
                'title' => 'Registration at Raffles Hotel',
            ],
            [
                'day' => 1,
                'time_1' => '09:00:00',
                'time_2' => '09:10:00',
                'title' => 'Opening Speech by PAQS YQS Chair',
            ],
            [
                'day' => 1,
                'time_1' => '09:10:00',
                'time_2' => '09:20:00',
                'title' => 'Welcome Speech by PAQS Chairman',
            ],
            [
                'day' => 1,
                'time_1' => '09:20:00',
                'time_2' => '10:00:00',
                'title' => 'Ice Breaking Game / Activity No. 1',
            ],
            [
                'day' => 1,
                'time_1' => '10:00:00',
                'time_2' => '10:30:00',
                'title' => 'Morning Tea & Networking Session',
            ],
            [
                'day' => 1,
                'time_1' => '10:30:00',
                'time_2' => '10:45:00',
                'title' => 'Presentation from Indonesian Quantity Surveyor Association (IQSI)',
            ],
            [
                'day' => 1,
                'time_1' => '10:45:00',
                'time_2' => '11:00:00',
                'title' => 'Presentation from Australian Institute of Quantity Surveyors (AIQS)',
            ],
            [
                'day' => 1,
                'time_1' => '11:00:00',
                'time_2' => '11:15:00',
                'title' => 'Presentation from Institute of Quantity Surveyors Sri Lanka (IQSSL)',
            ],
            [
                'day' => 1,
                'time_1' => '11:15:00',
                'time_2' => '11:30:00',
                'title' => 'Presentation from New Zealand Institute of Quantity Surveyors (NZIQS)',
            ],
            [
                'day' => 1,
                'time_1' => '11:30:00',
                'time_2' => '11:45:00',
                'title' => 'Presentation from Hong Kong Institute of Surveyors (HKIS)',
            ],
            [
                'day' => 1,
                'time_1' => '11:45:00',
                'time_2' => '12:00:00',
                'title' => 'Lunch & Friday Prayer',
            ],
            [
                'day' => 1,
                'time_1' => '12:00:00',
                'time_2' => '14:00:00',
                'title' => 'Ice Breaking Game / Activity No. 2',
            ],
            [
                'day' => 1,
                'time_1' => '14:00:00',
                'time_2' => '14:30:00',
                'title' => 'Presentation from Phillipines Institue of Certified Quantity Surveyors (PICQS)',
            ],
            [
                'day' => 1,
                'time_1' => '14:30:00',
                'time_2' => '14:45:00',
                'title' => 'Presentation from Institute of Surveyors, Engineers and Architects, Brunei (PUJA)',
            ],
            [
                'day' => 1,
                'time_1' => '14:45:00',
                'time_2' => '15:00:00',
                'title' => 'Presentation from Royal Institution of Surveyors Malaysia (RISM)',
            ],
            [
                'day' => 1,
                'time_1' => '15:15:00',
                'time_2' => '15:30:00',
                'title' => 'Presentation from Singapore Institute of Surveyors and Valuers (SISV)',
            ],
            [
                'day' => 1,
                'time_1' => '15:30:00',
                'time_2' => '15:45:00',
                'title' => 'Afternoon Tea Break',
            ],
            [
                'day' => 1,
                'time_1' => '15:45:00',
                'time_2' => '16:00:00',
                'title' => 'Closing Speech by IQSI Chairman',
            ],
            [
                'day' => 1,
                'time_1' => '16:30:00',
                'time_2' => '16:15:00',
                'title' => 'Briefing on Day 2 event: Site Visit & Dinner',
            ],
            [
                'day' => 1,
                'time_1' => '17:30:00',
                'time_2' => NULL,
                'title' => 'Casual Dinner',
            ],
            [
                'day' => 1,
                'time_1' => '19:30:00',
                'time_2' => NULL,
                'title' => 'Evening activity',
            ],
            [
                'day' => 2,
                'time_1' => '08:30:00',
                'time_2' => '09:00:00',
                'title' => 'Meet and depart for Site Visit',
            ],
            [
                'day' => 2,
                'time_1' => '09:00:00',
                'time_2' => '12:00:00',
                'title' => 'Site Visit to MRT Phase 2',
            ],
            [
                'day' => 2,
                'time_1' => '12:00:00',
                'time_2' => '13:30:00',
                'title' => 'Lunch',
            ],
            [
                'day' => 2,
                'time_1' => '13:30:00',
                'time_2' => '17:00:00',
                'title' => 'Visit to Iconic Attraction',
            ],
            [
                'day' => 2,
                'time_1' => '17:00:00',
                'time_2' => '19:00:00',
                'title' => 'Depart back to Raffles Hotel',
            ],
        ]);

        Programme::insert([
            [
                'name' => 'YQS Workshop',
                'date' => '2025-08-23',
                'time_start' => '08:00',
                'time_end' => '17:00',
                'information' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dinner & Fun Games',
                'date' => '2025-08-23',
                'time_start' => '08:00',
                'time_end' => '24:00',
                'information' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Technical Visit & City Tour',
                'date' => '2025-08-23',
                'time_start' => '08:00',
                'time_end' => '17:00',
                'information' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Golf Tournament',
                'date' => '2025-08-23',
                'time_start' => '07:30',
                'time_end' => '12:00',
                'information' => 'Pre-Congres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Committee Meeting',
                'date' => '2025-08-23',
                'time_start' => '13:00',
                'time_end' => '17:00',
                'information' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Board Meeting',
                'date' => '2025-08-24',
                'time_start' => '08:00',
                'time_end' => '24:00',
                'information' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Roadmap::insert([
            [
                'id' => 1,
                'title' => 'Team identification & initial planning',
                'description' => 'Formation of the committee and division of tasks, identifying the logistical needs of the congress (venue, accommodation, transportation, technical), and preparing sponsorship packages and proposals.',
                'date' => '2024-09-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'Launch of the official website & digital campaign',
                'description' => 'Launching the official website and digital campaign, preparing the list of invitations and sponsorships, pre-booking the venue, and Offline Workshops.',
                'date' => '2024-10-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Digital promotion and pre-event preparations',
                'description' => 'Content publication through the website and social media. Distribution of monthly newsletters. Sending invitations to speakers and sponsors. Finalizing the logo and event theme. Searching for primary sponsors and negotiating',
                'date' => '2024-11-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Webinar dan Call for Papers',
                'description' => 'Starting monthly webinars with the distribution of press releases to local and international media, promotions on social media and the website, as well as finalizing event branding and promotional materials. Call for Papers, announcement of the availability of papers',
                'date' => '2024-12-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'Fundraising & Networking',
                'description' => 'Holding networking dinners/breakfasts with potential sponsors and industry executives. Opening online registration for participants and donation campaigns on the official website. Initial logistics coordination for confirmed speakers. Preparation for the Charity Gala Dinner as part of fundraising efforts',
                'date' => '2025-01-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'Panel Discussions and Roadshow',
                'description' => 'Online panel discussions with industry leaders, seminar roadshows, sponsor negotiations, and regular updates of event information on the website and social media',
                'date' => '2025-02-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => 'Promotion and Innovation Competency',
                'description' => 'Launching technology and design innovation competitions for students and young professionals, accompanied by monthly webinars, social media campaigns, technical coordination, and press release distribution.',
                'date' => '2025-03-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'title' => 'Crowdfunding & Competency Innovation',
                'description' => 'Launching an online crowdfunding campaign for public fundraising, organizing innovation competitions, finalizing presentation materials, and coordinating with media partners.',
                'date' => '2025-03-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'title' => 'Fundraising & Workshop',
                'description' => 'Conducting the Charity Gala Dinner and other fundraising events. Thematic workshops in major cities to increase engagement. Ticket and merchandise sales to raise additional funds. Sponsorship publication across all event promotional media',
                'date' => '2025-04-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'title' => 'Countdown Campaign & Offline Promotion',
                'description' => 'The countdown campaign begins 60 days before the event with teasers and videos on social media. Event guidelines are sent to speakers, technical meetings are conducted, and additional promotion is carried out through media partners and industry influencers',
                'date' => '2025-05-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'title' => 'Final Logistics and Coordination',
                'description' => 'Finalizing logistics and technical arrangements, coordinating with sponsors, closing participant registrations, and placing sponsors in promotional materials',
                'date' => '2025-06-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'title' => 'Final Preparations and Event Execution',
                'description' => 'Confirming speaker requirements and arrivals, briefing the committee and service providers, placing sponsor branding, coordinating sponsor booths, and executing the PAQS International Congress 2025 according to schedule',
                'date' => '2025-07-01',
                'icon' => "<x-sui-document />",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        Speaker::insert([
            [
                'name' => 'Prof. Dr. (H.C.). Ir. Mohammed Ali Berawi, M.Eng.Sc., Ph.D.',
                'title' => NULL,
                'image' => 'Prof. Berawi.png',
                'description' => "Prof. Dr. (H.C.) Ir. Mohammed Ali Berawi, M.Eng.Sc, Ph.D, currently serves as the Deputy for Green and Digital Transformation at the Nusantara Capital Authority. He has also been actively teaching in the Department of Civil Engineering, Faculty of Engineering, Universitas Indonesia, since 2008. Previously, Prof. Ali Berawi held the position of Secretary to a Member of the Advisory Council to the President of Indonesia (2020–2022).<br> Prof. Mohammed Ali Berawi completed his doctoral studies in Value Engineering and Innovation at Oxford Brookes University, UK. He holds a professional engineering degree (Ir.) from Universitas Indonesia and a Master of Engineering Science (M.Eng.Sc.) from the University of Malaya. In 2024, he was awarded an Honorary Doctorate from Peter the Great Saint Petersburg Polytechnic University, Russia.<br>Prof. Mohammed Ali Berawi is a professor in the Department of Civil Engineering, Faculty of Engineering, Universitas Indonesia. He has also been a Visiting Scholar at the Department of Civil and Environmental Engineering, University of Washington, USA (2017), and a Visiting Professor at the University of Malaya, Malaysia (2023–2024). Additionally, he served as a Professor at the Graduate School of Industrial Economics, Peter the Great Saint Petersburg Polytechnic University, Russia (2019–2023). Prof. Mohammed Ali Berawi has been listed among the Top 2% of the World's Best Scientists by Elsevier and Stanford University for four consecutive years, from 2021 to 2024.<br>He is the Chairperson of the Indonesian Association of Lecturers (ADI) (2022–2027), Chair of the Supervisory Board for the Forum of Science and Technology Professional Organizations (FOPI) (2023–2026), Director of the Center for Sustainable Infrastructure Development (CSID), Executive Director of the ASEAN University Network for Sustainable City and Urban Development (AUN-SCUD), and Chair of the Smart Cities Working Group under the Association of Pacific Rim Universities (APRU-SCL)."
            ],
            [
                'name' => 'Eugene Seah (A/Prof Dr)',
                'title' => 'CEO DLS Consultancy Pte Ltd',
                'image' => "Dr Eugene Seah's.png",
                'description' => "Eugene holds over 25 years of experience in Project Management, Cost and Contracts Management, Sustainability, Digital and Technology as well as Construction Law and Alternate Dispute Resolution. He has supervision and works a wide range of developments including commercial buildings, hotels, residential, institutional, airports and infrastructure project, industrial, mobility, TOD and sports complexes. He has vast experience in the construction sector and is well respected in the academic community as well. Eugene taught at the National University of Singapore (MSc PM) since 2008 to 2023 and volunteers teaching at other Local and Foreign Universities. In his past companies, Eugene was tasked to build up and carry out cost research and cost data analysis and was in charge of the Building and M&E Cost data build up. In his experience, he has worked in international design and engineering companies and has experience in managing public listed companies His strengths are his networks, the understanding of people as a Coach and his business entrepreneurship, keeping abreast with the latest in the AEC sector."
            ],
            [
                'name' => 'SR DR ONG SEE LIAN, KMN',
                'title' => 'Director & Strategic Advisor Turner & Townsend Malaysia',
                'image' => 'ONG SEE LIAN.png',
                'description' => "Sr. Dr. Ong has an illustrious career spanning over 50 years in both the public and private sectors of the property and construction industry. He is currently the Director and Strategic Adviser of Turner and Townsend Malaysia.<br>Sr. Dr. Ong is an active member of several professional institutions in Malaysia and internationally and has served in various capacities. Some of his notable appointments are:<ul><li>President of the Royal Institution of Surveyors Malaysia (RISM) for 2003 – 2004 session.</li><li>Chairman of PAQS from 2003 to 2005.</li><li>Board member of the Board of Quantity Surveyors Malaysia (2003-2010)</li><li>130th Global President of the Royal Institution of Chartered Surveyors (2011-2012). He is the first non-British passport holder, first Asian and the first Malaysian to be elected as the Global President in the 143-year history of RICS.</li><li>Chairman of Commission 10 (Construction Economics and Management) of Federation of International Surveyors (FIG), (2015-2018).</li><li>Chairman of Standard Setting Committee of International Construction Management Standard (ICMS) – (2015 to 2020).</li><li>Member of Technical Committee on the revision of CIDB Standard Forms of Contract (from 2022 until now)</li><li>Member of Expert Committee of the Asian International Arbitration Centre (AIAC) Standard Forms of Contract</li></ul>"
            ],
        ]);
    }
}
