<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HotelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Hotel::insert([
            [
                "id" => 1,
                "name" => "Ascott Kuningan Jakarta",
                "star" => 5,
                "telephone" => "02130060288",
                "location" => "https://maps.app.goo.gl/2hDkjgPZUE2GxFVNA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 2,
                "name" => "Somerset Grand Citra",
                "star" => 5,
                "telephone" => "02129956888",
                "location" => "https://maps.app.goo.gl/iSAELWMdvGuqFjVa6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 3,
                "name" => "Oakwood Premier Cozmo",
                "star" => 5,
                "telephone" => "02125542300",
                "location" => "https://maps.app.goo.gl/Kq7wXFnoQt2yijog9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 4,
                "name" => "JW Mariott Hotel",
                "star" => 5,
                "telephone" => "02157988888",
                "location" => "https://maps.app.goo.gl/5M59iHnjPxpxYVJd6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 5,
                "name" => "The Ritz-Carlton Jakarta, Mega Kuningan",
                "star" => 5,
                "telephone" => "02125518888",
                "location" => "https://maps.app.goo.gl/ATK6Hk3gWTxPcYrZ9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 6,
                "name" => "Four Seasons",
                "star" => 5,
                "telephone" => "02122771888",
                "location" => "https://maps.app.goo.gl/NvtwDR8De3cTCQzh9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 7,
                "name" => "The Grove Suites by Grand Aston",
                "star" => 5,
                "telephone" => "02129941880",
                "location" => "https://maps.app.goo.gl/Py4wFsEeoBpgbPY4A",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 8,
                "name" => "Hotel Indonesia Kempinski Jakarta",
                "star" => 5,
                "telephone" => "02123583800",
                "location" => "https://maps.app.goo.gl/WnzeFd3A4V7MMNBT8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 9,
                "name" => "The Westin Jakarta",
                "star" => 5,
                "telephone" => "02127887788",
                "location" => "https://maps.app.goo.gl/zgeadkgexv8zFyjF9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 10,
                "name" => "Gran Melia Jakarta",
                "star" => 5,
                "telephone" => "0215268080",
                "location" => "https://maps.app.goo.gl/rbKEd9hnLtVwGafLA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 11,
                "name" => "JS Luwansa ",
                "star" => 4,
                "telephone" => "02129543030",
                "location" => "https://maps.app.goo.gl/1tLftrp7giNXgAFq6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 12,
                "name" => "Mangkuluhur ARTOTEL Suites",
                "star" => 4,
                "telephone" => "0215268833",
                "location" => "https://maps.app.goo.gl/F1sKj3Dz9Y5YXC7v5",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 13,
                "name" => "Mercure Jakarta Gatot Subroto",
                "star" => 4,
                "telephone" => "02150825400",
                "location" => "https://maps.app.goo.gl/1BuNYyyg1skU9ceu7",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 14,
                "name" => "Novotel Jakarta Cikini",
                "star" => 4,
                "telephone" => "02131937777",
                "location" => "https://maps.app.goo.gl/Nbe3d3A3nfanM81c6",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 15,
                "name" => "Aryaduta Menteng",
                "star" => 4,
                "telephone" => "02123521234",
                "location" => "https://maps.app.goo.gl/DufsvCUFN1FCknrZ8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 16,
                "name" => "Citadines Sudirman Jakarta",
                "star" => 4,
                "telephone" => "02139738080",
                "location" => "https://maps.app.goo.gl/xUEKmA4YYrMM1vqE9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 17,
                "name" => "Habitare Rauna Jakarta",
                "star" => 4,
                "telephone" => "+628118129533",
                "location" => "https://maps.app.goo.gl/g6qXvrNNVuGjMvg66",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 18,
                "name" => "Ayaka Suites",
                "star" => 3,
                "telephone" => "02129037380",
                "location" => "https://maps.app.goo.gl/AED5Fisf5UTvYrWS9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 19,
                "name" => "Miers Kuningan, ARTOTEL Curated",
                "star" => 3,
                "telephone" => "02157851751",
                "location" => "https://maps.app.goo.gl/FMKynKjiPcgnfy3HA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 20,
                "name" => "D'Bamboo Suites",
                "star" => 3,
                "telephone" => "0811-9004-815",
                "location" => "https://maps.app.goo.gl/MhvDuYddyFi43Gb58",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 21,
                "name" => "Hotel D' Prima",
                "star" => 3,
                "telephone" => "02129201234",
                "location" => "https://maps.app.goo.gl/9MgEemHQX4VzqN5g9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 22,
                "name" => "Rasuna Icon Hotel",
                "star" => 3,
                "telephone" => "0215201642",
                "location" => "https://maps.app.goo.gl/crtT2a6pYsEtWAdTA",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 23,
                "name" => "Avissa Suites",
                "star" => 3,
                "telephone" => "02152960022",
                "location" => "https://maps.app.goo.gl/krxo9Kj2MpnC16CA9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 24,
                "name" => "favehotel Gatot Subroto Jakarta",
                "star" => 3,
                "telephone" => "02129419888",
                "location" => "https://maps.app.goo.gl/toVwDAmMjb6gkxKE8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 25,
                "name" => "Yello Hotel Manggarai",
                "star" => 3,
                "telephone" => "02130428888",
                "location" => "https://maps.app.goo.gl/y2jmpLgpHXJAP65M9",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 26,
                "name" => "Pomelotel Patra Kuningan Jakarta",
                "star" => 3,
                "telephone" => "02183709588",
                "location" => "https://maps.app.goo.gl/5w2eWhd497ZHAHzb7",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 27,
                "name" => "Daun Residence Kuningan",
                "star" => 3,
                "telephone" => "02125984108",
                "location" => "https://maps.app.goo.gl/YARYc2uqHMEmBtuT8",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "id" => 28,
                "name" => "Nostoi",
                "star" => 3,
                "telephone" => "081280393849",
                "location" => "https://maps.app.goo.gl/JCumnJ5vBspqKNEz5",
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
